name: Trigger packagist regeneration

on: 
  push:
    branches: 
      - master

jobs: 
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch update event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PACKAGIST_TRIGGER_PAT }}
          repository: ${{github.repository_owner}}/packagist
          event-type: update
          client-payload: '{"repo": "git://github.com/${{github.repository}}.git"}'
